# 异常

Python 使用异常对象来表示异常状态，并在遇到错误时引发异常。

### raise 语句

引发异常，可使用 raise 语句，并将一个类（必须是 Exception 的子类）或实例作为参数。

#### 捕获异常

```python
try: 
     x = int(input('Enter the first number: ')) 
     y = int(input('Enter the second number: ')) 
     print(x / y) 
except ZeroDivisionError: 
 	 print("The second number can't be zero!") 
```

#### 触发异常

```python
try: 
	1/0 
except ZeroDivisionError: 
	raise ValueError 
# 这种想要触发其他异常，会导致进入 except 子句的异常将被作为异常上下文存储起来，并出现在最终错误消息中
Traceback (most recent call last): 
 File "<stdin>", line 2, in <module> 
ZeroDivisionError: division by zero 
    
Traceback (most recent call last): 
 File "<stdin>", line 4, in <module> 
ValueError

# 可以使用 raise ... from ... 语句来提高异常上下文，也可以使用 None 禁用上下文
raise ValueError from None
# 此时就不会显示 ZeroDivisionError 异常
```

**Tips：想要捕获多个异常时，可以使用元组将多个异常包裹起来**

```python
try: 
 print('A simple task') 
except: 
 print('What? Something went wrong?') 
else: 
 print('Ah ... It went as planned.') 

# 此处只有在没有异常发生时，才会执行 else 代码块

try:
    ...
finally:
    ...
# finally 不管 try 中发生任何异常都会执行 finally，常用在发生异常时执行清理工作
```

